- name: Create olpc-scripts directory
  file: path={{ item }}
        owner=root
        group=root
        mode=0755
        state=directory
  with_items:
    - /etc/sysconfig/olpc-scripts/
    - /etc/sysconfig/olpc-scripts/setup.d/installed/

- name: Set hostname
  template: backup=yes
            dest=/etc/hostname
            src=network/hostname.j2
            owner=root
            mode=0644

- name: Create xs network flags
  template: backup=yes
            src=network/{{ item }}.j2
            dest=/etc/sysconfig/{{ item }}
            mode=0644
  with_items:
    - xs_wan_device
    - xs_lan_device
    - xs_domain_name
  tags:
    - network-discover

- name: Configure /etc/sysconfig/network
  template: backup=yes
            src=network/sysconfig.network.j2
            dest=/etc/sysconfig/network
            owner=root
            group=root
            mode=0644

#TODO: Use vars instead of hardcoded values
- name: Configure LAN in /etc/hosts
  lineinfile: backup=yes
              dest=/etc/hosts
              regexp='^172\.18\.96\.1'
              line='172.18.96.1            {{ xsce_hostname }}.{{ xsce_domain }}      {{ xsce_hostname }}'
              owner=root
              group=root
              mode=0644
  when: 'xsce_lan_iface != "none"'

- name: Configure WAN in /etc/hosts
  lineinfile: backup=yes
              dest=/etc/hosts
              line='{{ ansible_default_ipv4.address }}            {{ xsce_hostname }}.{{ xsce_domain }}      {{ xsce_hostname }}'
              owner=root
              group=root
              mode=0644
  when: 'xsce_lan_iface == "none" and ansible_default_ipv4.address is defined'

- name: Configure lo in /etc/hosts
  lineinfile: backup=yes
              dest=/etc/hosts
              regexp='^127\.0\.0\.1'
              line='127.0.0.1            localhost.localdomain   localhost   {{ xsce_hostname }}'
              owner=root
              group=root
              mode=0644

- name: Remove lan interface
  file: state=absent
        dest=/etc/sysconfig/network-scripts/ifcfg-LAN
  when: xsce_lan_iface == "none"

- name: Configure lan interface
  template: backup=yes
            src=network/ifcfg.j2
            dest=/etc/sysconfig/network-scripts/ifcfg-LAN
  when: 'xsce_lan_iface != "none"'

# Too do handle more than one detected interface
- name: enslaving LAN device to Bridge
  template: src=network/ifcfg-slave.j2
            dest=/etc/sysconfig/network-scripts/ifcfg-{{discovered_lan_iface}}
  when: 'discovered_lan_iface != "" and detect_slaves'

# supply an ifcfg if no gateway detected but wan_ip is set
# set user_wan_iface: <device> and use wan_* for static info
- name: Supply wan interface file
  template: src=network/ifcfg-WAN.j2
            dest=/etc/sysconfig/network-scripts/ifcfg-{{xsce_wan_iface}}
  when: 'xsce_wan_iface != "none" and wan_ip != "dhcp"'

- include: NM.yml
  when: 'xsce_wan_iface != "none" and wan_ip != "dhcp"'

- include: named.yml
  tags:
    - named
    - network

- include: dhcpd.yml
  tags:
    - dhcpd
    - network

- include: squid.yml
  tags:
    - squid
    - network

- include: wondershaper.yml
  tags:
    - wondershaper
    - network

- include: iptables.yml
  tags:
    - iptables
    - network

- name: Create gateway flag
  shell: echo 1 > /etc/sysconfig/olpc-scripts/setup.d/installed/gateway
         creates=/etc/sysconfig/olpc-scripts/setup.d/installed/gateway

- include: NM.yml
  tags:
    - network
