- name: Install Fedora specifc packages
  yum: name={{ item }}
       state=present
  with_items:
   - mtd-utils

- name: Install optional exFAT packages for Fedora
  shell: yum --enablerepo=rpmfusion-free-updates install exfat-utils fuse-exfat
  when: exFAT_enabled == "True"
