- name: Base Server Installed
  command: echo Base Server Installed

- name: Restart xsce-cmdsrv service
  service: name=xsce-cmdsrv
           state=restarted
  when: not installing

- name: Restart httpd
  service: name=httpd
           state=restarted
  when: not installing

- name: Setting Graphical Login
  file: path=/etc/systemd/system/default.target
        src=/lib/systemd/system/graphical.target
        state=link
        force=yes
  when: installing

# If we got here we're done
- name: Create hidden xsce-prepped file 
  file: dest=/.xsce-prepped
        state=touch
  when: installing

