- include: admin-user.yml
  tags:
    - base

- include: access.yml
  tags:
    - base

- name: Add xsce-admin parameters to ini file
  ini_file: dest='{{ service_filelist }}'
            section=xsce-admin
            option='{{ item.option }}'
            value='{{ item.value }}'
  with_items:
    - option: name
      value: xsce-admin
    - option: description
      value: '"Admin User"'
    - option: xsce_admin_user
      value: "{{ xsce_admin_user }}"
