# Setup specific to the Raspberry Pi
##  DISCOVER ADAPTERS   ######
- name: Detect an i2c rtc if it exists
  shell: "i2cdetect -y 1 | grep -e 68 -e UU | wc | gawk '{print $1}'"
  register: rtc_response
  ignore_errors: yes

- name: Record whether rtc hardware was detected
  set_fact:
     rtc_id: "DS3231"
  when:  rtc_response.stdout > "0"

#
# kernel 3.18 requires a change to the device tree (and reboot)
- name: Check for needing to enable i2c rtc device in config.txt
  lineinfile: dest=/boot/config.txt
              regexp="^#device_tree_param=i2c1=on"
              line="device_tree_param=i2c1=on" 
              backrefs=yes
  register: rpiconfig

- name: Reboot if the config.txt was changed
  command: /sbin/reboot
  when: rpiconfig.changed
  async: 300
  poll: 120

- name: Load the modules for the RTC
  template: dest=/etc/modules-load.d/rtc.conf
            src=rtc.conf

- name: Instantiate a connection to i2c RTC
  lineinfile: dest=/etc/rc.d/rc.local
              line="echo ds1307 0x68 > /sys/class/i2c-adapter/i2c-1/new_device"
              create=yes
  when:  rtc_id  == "DS3231" 

- name: Delete instantiation if rtc is removed
  lineinfile: dest=/etc/rc.d/rc.local
              regexp="echo ds1307 0x68 > /sys/class/i2c-adapter/i2c-1/new_device"
              state=absent
  when:  rtc_id  != "DS3231" 

