- name: Checking for ifcfg-WAN file
  stat: path=/etc/sysconfig/network-scripts/ifcfg-WAN
  register: has_ifcfg_WAN

- name: Setting ifcfg-WAN True
  set_fact:
    has_WAN: True
  when: has_ifcfg_WAN.stat.exists

# DETECT -- gateway and wireless
- name: Get a list of slaves from previous config
  shell: "egrep -rn BRIDGE=br0 /etc/sysconfig/network-scripts/ifcfg-* | gawk -F'[-:]' '{print $3}'"
  register: ifcfg_slaves
  ignore_errors: True
  changed_when: False

# returns list of paths
- name: Find gateway config based on device
  shell: "egrep -rn {{ device_gw }} /etc/sysconfig/network-scripts/ifcfg* | gawk -F ':' '{print $1}'"
  register: ifcfg_gw_device
  ignore_errors: True
  changed_when: False
  when: device_gw != "none"

# last match wins
- name: Setting has ifcfg gw based on device if found
  set_fact:
    has_ifcfg_gw: "{{ item|trim }}"
  ignore_errors: True
  when: ifcfg_gw_device.stdout_lines is defined and item|trim != "" and item|trim != "/etc/sysconfig/network-scripts/ifcfg-LAN"
  with_items:
      - "{{ ifcfg_gw_device.stdout_lines }}"

# returns path
- name: Find active gateway config based on macaddress
  shell: "egrep -irn {{ ansible_default_ipv4.macaddress }} /etc/sysconfig/network-scripts/ifcfg* | gawk -F ':' '{print $1}' | head -n 1"
  register: ifcfg_gw_mac
  ignore_errors: True
  changed_when: False
  when: 'ansible_default_ipv4.gateway is defined'

- name: Set has ifcfg gw based on on macaddress if found
  set_fact:
    has_ifcfg_gw: "{{ ifcfg_gw_mac.stdout|trim }}"
  when: ifcfg_gw_mac is defined and ifcfg_gw_mac.stdout != ""

# could use something else
- name: Find wifi gateway config if present
  shell: egrep -rn ESSID /etc/sysconfig/network-scripts/ifcfg* | gawk -F ':' '{print $1}' | gawk -F '/' '{print $5}'
  register: ifcfg_WAN_wifi
  ignore_errors: True

#returns file name
- name: Setting has_wifi_gw based on ESSID if found
  set_fact:
    has_wifi_gw: "{{ item|trim }}"
  when: ifcfg_WAN_wifi.changed and item|trim != ""
  with_items:
      - "{{ ifcfg_WAN_wifi.stdout_lines }}"

- name: Finding device for wifi AP gateway
  shell: egrep -rn DEVICE /etc/sysconfig/network-scripts/{{ has_wifi_gw }} |  gawk -F '=' '{print $2}'
  register: AP_device
  when: has_wifi_gw != "none" and has_ifcfg_gw != "none"

- name: Setting wifi device
  set_fact:
    ap_device: "{{ AP_device.stdout }}"
  when: AP_device.stdout is defined and AP_device.stdout != ""

- name: XO override 2 wifi on LAN
  set_fact:
      ap_device: "eth0"
  when: xsce_wan_iface != "eth0" and discovered_wireless_iface != "none" and xo_model == "XO-1.5"

#unused
- name: Get a list of ifcfg files to delete
  shell: "ls -1 /etc/sysconfig/network-scripts/ifcfg-* | grep -v -e ifcfg-lo  -e ifcfg-WAN -e {{ has_wifi_gw }}"
  register: ifcfg_files
  changed_when: False
  ignore_errors: True
  when: num_lan_interfaces >= "1" or xsce_wireless_lan_iface != "none"
#
