- name: Install munin package
  yum: name={{ item }}
       state=present
  with_items:
    - munin
    - munin-node
  tags:
    - download

- name: Copy munin config file
  template: backup=yes
            src=munin.conf.j2
            dest=/etc/munin/munin.conf
            owner=root
            group=root
            mode=0644

- name: Create admin user
  htpasswd: path=/etc/munin/munin-htpasswd
            name=admin
            password=munindxs
            create=yes
            state=present

- name: Enable munin-node service
  service: name=munin-node
           enabled=yes

- name: Add munin to service list
  ini_file: dest='{{ service_filelist }}'
            section=munin
            option='{{ item.option }}'
            value='{{ item.value }}'
  with_items:
    - option: name
      value: munin
    - option: description
      value: '"Munin is a networked resource monitoring tool that can help analyze resource trends and \"what just happened to kill our performance?\" problems."'
    - option: installed
      value: "{{ munin_install }}"
    - option: enabled
      value: "{{ munin_enabled }}"
